#!/bin/bash
# Generated by Copilot
# Post context update to GitHub Issues sync channel

REPO="Stan2891/bmparts-ai"
SYNC_ISSUE=6

# Usage: ./copilot-sync.sh "message"
MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
    echo "Usage: ./copilot-sync.sh \"Your message here\""
    exit 1
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
FORMATTED="**[$TIMESTAMP]** $MESSAGE"

gh issue comment $SYNC_ISSUE --repo $REPO --body "$FORMATTED"
echo "Posted to issue #$SYNC_ISSUE"
