#!/bin/bash
# Generated by Copilot - Export memory to repo for GitHub.com Copilot
# Run via cron every hour

REPO_DIR="/home/stan/bmparts-ai"
MEMORY_FILE="$REPO_DIR/.github/memory-export.md"

# Get top 50 important memories
curl -s -X POST http://127.0.0.1:8000/search \
  -H "Content-Type: application/json" \
  -d '{"query": "important context business", "limit": 50}' | \
  jq -r '.results[] | "- [\(.category)] \(.text)"' > /tmp/memories.txt

# Build markdown file
cat > "$MEMORY_FILE" << HEADER
# Memory Export for GitHub.com Copilot
**Auto-generated:** $(date -Iseconds)
**Source:** gpt-memory:8000 ($(curl -s http://127.0.0.1:8000/health | jq -r '.points_count') memories)

---

## Key Memories
$(cat /tmp/memories.txt)
HEADER

# Commit and push if changed
cd "$REPO_DIR"
if git diff --quiet "$MEMORY_FILE" 2>/dev/null; then
  echo "No changes"
else
  git add "$MEMORY_FILE"
  git -c credential.helper='!gh auth git-credential' commit -m "chore: auto-export memory $(date +%Y-%m-%d-%H%M)"
  git -c credential.helper='!gh auth git-credential' push origin main
  echo "Memory exported to repo"
fi
