#!/bin/bash
# Generated by Copilot
# Generate readable memory context for GitHub.com Copilot

OUTPUT="/home/stan/bmparts-ai/.github/memory-context.md"
MEMORY_URL="http://127.0.0.1:8000/export"

# Fetch memories
MEMORIES=$(curl -s "$MEMORY_URL")
COUNT=$(echo "$MEMORIES" | jq -r '.count')
TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

cat > "$OUTPUT" << EOF
# 🧠 BMParts Memory Context
> Auto-synced: $TIMESTAMP | Total: $COUNT memories

---

## Business Context
EOF

echo "$MEMORIES" | jq -r '.memories[] | select(.category == "business" or (.text | test("BMParts|Zoho|WooCommerce|inventory|wholesale"; "i"))) | "- " + .text' | head -20 >> "$OUTPUT"

cat >> "$OUTPUT" << EOF

---

## Infrastructure & Services
EOF

echo "$MEMORIES" | jq -r '.memories[] | select(.category == "infrastructure" or (.text | test("port|server|nginx|MCP|memory|API"; "i"))) | "- " + .text' | head -15 >> "$OUTPUT"

cat >> "$OUTPUT" << EOF

---

## People & Contacts
EOF

echo "$MEMORIES" | jq -r '.memories[] | select(.category == "contacts" or (.text | test("Stan|Selena|family|wife|mother"; "i"))) | "- " + .text' | head -10 >> "$OUTPUT"

cat >> "$OUTPUT" << EOF

---

## Rules & Preferences
EOF

echo "$MEMORIES" | jq -r '.memories[] | select(.text | test("must|always|never|prefer|want"; "i")) | "- " + .text' | head -10 >> "$OUTPUT"

cat >> "$OUTPUT" << EOF

---

## Recent Sessions
EOF

echo "$MEMORIES" | jq -r '.memories[] | select(.text | test("Dec 2025|session|Session"; "i")) | "- " + .text' | head -5 >> "$OUTPUT"

echo "✅ Generated: $OUTPUT ($COUNT memories)"
