#!/usr/bin/env python3
# Generated by Copilot
"""
Issue #7 Comment Monitor
Detects new comments and posts notification summary.
"""

import os
import json
import requests

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ.get("REPO", "Stan2891/bmparts-ai")
ISSUE_NUMBER = os.environ.get("ISSUE_NUMBER", "7")
STATE_FILE = ".github/issue-monitor/state.json"

HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28"
}

def load_state():
    """Load last known comment ID from state file."""
    try:
        with open(STATE_FILE, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {"last_comment_id": 0}

def save_state(state):
    """Save state to file."""
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)

def get_comments():
    """Fetch all comments for the issue."""
    url = f"https://api.github.com/repos/{REPO}/issues/{ISSUE_NUMBER}/comments"
    response = requests.get(url, headers=HEADERS, timeout=15)
    response.raise_for_status()
    return response.json()

def post_comment(body):
    """Post a comment to the issue."""
    url = f"https://api.github.com/repos/{REPO}/issues/{ISSUE_NUMBER}/comments"
    response = requests.post(url, headers=HEADERS, json={"body": body}, timeout=15)
    response.raise_for_status()
    return response.json()

def main():
    state = load_state()
    last_id = state.get("last_comment_id", 0)
    
    comments = get_comments()
    
    # Filter: new comments only, exclude bot comments entirely (anti-loop)
    new_comments = [
        c for c in comments
        if c["id"] > last_id and c["user"]["login"] != "github-actions[bot]"
    ]
    
    if not new_comments:
        print(f"No new human comments since ID {last_id}")
        return
    
    print(f"Found {len(new_comments)} new human comment(s)")
    
    # Build notification message
    lines = ["🔔 **New Comment(s) Detected on Issue #7**\n"]
    for c in new_comments:
        author = c["user"]["login"]
        created = c["created_at"]
        body = c["body"][:200] + ("..." if len(c["body"]) > 200 else "")
        link = c["html_url"]
        lines.append(f"**@{author}** at `{created}`:\n> {body}\n[View →]({link})\n")
    
    notification = "\n".join(lines)
    notification += "\n---\n_Automated monitor — GitHub Actions_"
    post_comment(notification)
    print("Notification posted")
    
    # Update state to latest comment ID (including bot comments for baseline)
    max_id = max(c["id"] for c in comments)
    state["last_comment_id"] = max_id
    save_state(state)
    print(f"State updated: last_comment_id = {max_id}")

if __name__ == "__main__":
    main()
